x-common-cpu-config: &cpu-config
  logging:
    options:
      max-size: "50mb"
  restart: always
  depends_on:
    - redis
  env_file:
    - .env.celery
  volumes:
    - ./cos:/cos
x-common-gpu-config: &gpu-config
  <<: *cpu-config
  deploy:
    resources:
      reservations:
        devices:
          - driver: "nvidia"
            count: "all"
            capabilities: ["gpu"]

version: "3"

services:
  db:
    image: mysql:5.7
    logging:
      options:
        max-size: "50mb"
    restart: always
    environment:
      MYSQL_DATABASE: mercury
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      default:
        aliases:
          - mercury_db
  redis:
    image: redis:latest
    logging:
      options:
        max-size: "50mb"
    restart: always
    volumes:
      - ./data/redis:/data
    networks:
      default:
        aliases:
          - mercury_redis
    ports:
      - "9045:6345"
    command: redis-server --port 6345 --requirepass ${REDIS_PASSWORD}
  mercury:
    image: mercury:v0.1-infer
    <<: *cpu-config
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - redis
      - db
    networks:
      default:
        aliases:
          - mercury_api
    ports:
      - "9033:3333"
  flower:
    image: flower:v0.1-infer
    <<: *cpu-config
    # TODO: auth
    environment:
      FLOWER_UNAUTHENTICATED_API: true
    ports:
      - "9055:5555"
    volumes:
      - ./data/flower:/app/flower/data

  # workers
  cosy_voice:
    image: cosy_voice:v0.1-infer
    <<: *gpu-config
  azure:
    image: azure:v0.1-infer
    <<: *cpu-config
    environment:
      AZURE_SPEECH_KEY: ${AZURE_SPEECH_KEY}
      AZURE_SPEECH_REGION: ${AZURE_SPEECH_REGION}
  rvc:
    image: rvc:v0.1-infer
    <<: *gpu-config
  srt:
    image: srt:v0.1-infer
    <<: *gpu-config
    environment:
      EMPTY_CACHE: true
  talking_head:
    image: talking_head:v0.1-infer
    <<: *gpu-config
    volumes:
      - ./cos:/cos
      - ./data/talking-head/dnr/exp_runs:/app/talking-head/dnr/exp_runs
      - ./data/talking-head/user-data:/app/talking-head/user-data

networks:
  default:
    driver: bridge